### ISSUE TITLE
Fragment usage

### ISSUE THREAD

**Issue by alexander-r-jaimy** [ohler55/agoo#101] opened 2021-05-21 09:22 UTC
Good morning,
I'd like to know of a valid example of using fragments.

When I try this it doesn't work:
![Screenshot from 2021-05-21 11-23-39](https://user-images.githubusercontent.com/60174868/119115077-0c6ea200-ba27-11eb-8c45-c21ada60d339.png)

even though this work perfectly fine:
![Screenshot from 2021-05-21 11-23-49](https://user-images.githubusercontent.com/60174868/119115115-18f2fa80-ba27-11eb-80eb-e2fd76370db5.png)

**Comment by ohler55** [comment] 2021-05-21 15:14
Fragments are supported. There is a test in test/graphql_test.rb named `test_post_fragment`.

I can look into why you example doesn't work though. It might take a couple of days before I can get to it though.

**Comment by ohler55** [comment] 2021-05-30 13:38
Started looking at this today. I am not able to reproduce the issue so I suspect there is something different about the request. Can you tell me what the HTTP POST request looks like or what the content type of the request is? Is it `application/graphql`?

**Comment by alexander-r-jaimy** [comment] 2021-05-31 09:29
Good afternoon,

We are working to provide you a reproducible example.
Meanwhile, this is the request that we are sending:

Request URL: http://localhost:6464/phrases
Request Method: POST
Status Code: 200 OK
Remote Address: 127.0.0.1:6464
Referrer Policy: strict-origin-when-cross-origin
accept: application/json, multipart/mixed
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Content-Length: 269\n 
content-type: application/json
Host: localhost:6464
Origin: http://localhost:6464
Referer: http://localhost:6464/iql.html
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Sec-GPC: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
`{"query":"\nfragment Phrase on Phrase {\n  code\n  usages\n  starting_english_phrase\n  is_system\n  rank\n}\n\nquery getPhrases($filters: PhrasesInput) {\n  phrases(filters: $filters) {\n    ...Phrase\n  }\n}\n","variables":{"filters":{}},"operationName":"getPhrases"}`

and this is the response that comes:

`{"data":{"phrases":[{},{},{},{},{},{}]}}`

I checked the test that you mention, on the example with fragments you are using application/json, but in any cases we tried with application/graphql and it doesn't really help.

I'm attaching some postman requests to demonstrate the issue:
![Screenshot from 2021-05-31 11-26-10](https://user-images.githubusercontent.com/60174868/120172442-5879cd80-c203-11eb-81da-5e226769acfb.png)
A valid graphql call
![Screenshot from 2021-05-31 11-27-03](https://user-images.githubusercontent.com/60174868/120172446-59126400-c203-11eb-8b3e-5d82e7aefac1.png)
Same but with fragment instead
![Screenshot from 2021-05-31 11-27-24](https://user-images.githubusercontent.com/60174868/120172447-59126400-c203-11eb-86f2-dfb001414ac6.png)

**Comment by ohler55** [comment] 2021-05-31 11:50
That helps. I'll try testing with JSON instead of GraphQL content.

**Comment by ohler55** [comment] 2021-05-31 23:32
That helped a lot although I would have expected to see an error on the fragment calls. There is a bug in the JSON parser which I will fix. In the mean time if possible you could try using a content type of `application/graphql`. If not I should have a fix in a day or two.

**Comment by alexander-r-jaimy** [comment] 2021-06-01 07:01
Thank you for your time for having a look on this issue.

Regarding `content-type: application/graphql`, I think there's another bug to it:
The first image with `"name not provided"` `"parse error"` is the outcome of trying to send a request with `application/graphql`.

And secondly, when I try to introspect the schema with this library [graphqurl](https://www.npmjs.com/package/graphqurl) 
and execute the following command `gq <url>  --introspect  > schema.json` it fails  with `unsupported content type`.

Noticeably, if I modify the command to export json rather than schema, it works, but then again I have to explicitly indicate the content-type:
gq <url> -H 'content-type: application/json'  --introspect --format json > schema.json

**Comment by ohler55** [comment] 2021-06-01 12:26
I'm not familiar with the gq tool so I'm not sure what the --introspect does but I will check it out and run some tests to get it all working.

I can't tell from the first image what the content was of the call. With that I could probably figure out what is going on.

**Comment by alexander-r-jaimy** [comment] 2021-06-01 12:39
ah, the content was the same as on other images, with or without fragment usage the error will be the same

**Comment by ohler55** [comment] 2021-06-01 12:43
I assume you mean the the same but in graphql format and not JSON, right?

**Comment by alexander-r-jaimy** [comment] 2021-06-01 12:45
yes indeed. it should download a SDL schema, instead of JSON

**Comment by ohler55** [comment] 2021-06-01 12:48
To nights homework for me will be to try out gq and see what is sent.

**Comment by alexander-r-jaimy** [comment] 2021-06-01 12:51
The following command:
`gq https://graphqlzero.almansi.me/api --introspect > schema.graphql` 
 downloads a schema. This is useful for generating typescript types to use in frontend frameworks - more automation

**Comment by ohler55** [comment] 2021-06-01 13:07
BTW, with Agoo you can also download the schema with `http://localhost:3000/graphql/schema` if the GraphQL endpoint is `http://localhost:3000/graphql`.

Can graphql-codegen be configured to generate ruby code as well?

**Comment by ohler55** [comment] 2021-06-03 00:08
The reason for the error in the first block is that just changing the header with gq does not change the content. The content is still JSON but the header claims to be graphql so Agoo attempts to parse as graphql and fails. Digging in to more but want to give you some preliminary feedback.

**Comment by ohler55** [comment] 2021-06-03 23:15
I haven't been able to reproduce the gq introspect issue. Curl works fine with the same query as does [graphiql](https://github.com/graphql/graphiql). I did uncover another issue with graphiql. A comment only request caused a crash which has been fixed. Just refresh the branch.

**Comment by ohler55** [comment] 2021-06-09 00:14
I plan on releasing these changes if I don't hear back from you by tomorrow.

**Comment by ohler55** [comment] 2021-06-13 15:21
Released and closing.

**Closed by ohler55** 2021-06-13 15:21 UTC
